### ISSUE TITLE
problem about API /list/trades

### ISSUE THREAD

**Issue by jonec76** [ace-exchange/ace-official-api-docs#1]
Hi, thanks for writing this API document, and there's some problem I want to ask.

I found that when I send the GET request via /list/trades/<currency_name>/<base currency_name>, the responses are all same in spite of using different currency pair.I am curious about how to get the specific trade correctly through the open API.

Thanks!

**Comment by ace-exchange** [comment]
You can use https://ace.io/polarisex/oapi/list/tradePrice to get all market pair prices.
